# Generated by Django 5.2.2 on 2026-08-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Agent display name', max_length=100)),
                ('persona', models.TextField(help_text='Description of the agent\'s personality and teaching style, e.g. "The Encouraging Friend"')),
                ('role', models.CharField(choices=[('interviewer', 'Job Interviewer'), ('local_guide', 'Local Guide'), ('pronunciation_specialist', 'Pronunciation Specialist'), ('general', 'General Tutor'), ('debate_partner', 'Debate Partner'), ('storyteller', 'Storyteller')], default='general', max_length=30)),
                ('accent', models.CharField(blank=True, default='', help_text='Accent style, e.g. "American", "British RP", "Neutral"', max_length=50)),
                ('dialect', models.CharField(blank=True, default='', help_text='Dialect, e.g. "Southern US", "Scottish"', max_length=50)),
                ('supported_languages', models.JSONField(default=list, help_text='List of language codes this agent supports, e.g. ["en", "es"]')),
                ('difficulty_scaling', models.BooleanField(default=True, help_text='Whether the agent automatically adjusts difficulty to user level')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this agent is available to users')),
                ('avatar_url', models.CharField(blank=True, default='', help_text="URL to the agent's avatar image", max_length=500)),
                ('system_prompt_template', models.TextField(help_text='Jinja2/format-string template for the system prompt. Available variables: {target_language}, {proficiency_level}, {user_name}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
                'db_table': 'agents_aiagent',
                'ordering': ['name'],
            },
        ),
    ]
