# Generated by Django 5.2.2 on 2026-08-10 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('audio', 'Audio'), ('text', 'Text'), ('video', 'Video')], default='text', max_length=10)),
                ('target_language', models.CharField(help_text='The language being practiced in this session', max_length=20)),
                ('proficiency_level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Mastery')], default='A1', max_length=2)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grammar_mistakes', models.JSONField(default=list, help_text='List of grammar mistakes made during the session')),
                ('new_vocabulary', models.JSONField(default=list, help_text='New vocabulary words encountered during the session')),
                ('pronunciation_scores', models.JSONField(default=dict, help_text='Pronunciation scores per word/phrase')),
                ('total_messages', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='', help_text='AI-generated session summary')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='agents.aiagent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Session',
                'verbose_name_plural': 'Learning Sessions',
                'db_table': 'sessions_learningsession',
                'ordering': ['-started_at'],
            },
        ),
    ]
