# Generated by Django 5.2.2 on 2026-08-10 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='user', max_length=10)),
                ('content', models.TextField(help_text='Text content of the message')),
                ('audio_url', models.CharField(blank=True, default='', help_text='URL to stored audio file for this message', max_length=500)),
                ('mode', models.CharField(choices=[('audio', 'Audio'), ('text', 'Text'), ('video', 'Video')], default='text', max_length=10)),
                ('feedback', models.JSONField(blank=True, default=None, help_text='Grammar corrections, suggestions, and pronunciation scores', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='learning_sessions.learningsession')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'conversations_message',
                'ordering': ['timestamp'],
            },
        ),
    ]
