# Generated by Django 5.2.2 on 2026-08-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_native_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='native_language',
            field=models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German'), ('japanese', 'Japanese'), ('mandarin', 'Mandarin Chinese'), ('portuguese', 'Portuguese'), ('italian', 'Italian'), ('korean', 'Korean'), ('arabic', 'Arabic'), ('amharic', 'Amharic (አማርኛ)'), ('oromo', 'Oromo (Afaan Oromoo)'), ('tigrinya', 'Tigrinya (ትግርኛ)'), ('somali', 'Somali (Soomaali)')], default='english', help_text="The user's native language", max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='target_language',
            field=models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German'), ('japanese', 'Japanese'), ('mandarin', 'Mandarin Chinese'), ('portuguese', 'Portuguese'), ('italian', 'Italian'), ('korean', 'Korean'), ('arabic', 'Arabic'), ('amharic', 'Amharic (አማርኛ)'), ('oromo', 'Oromo (Afaan Oromoo)'), ('tigrinya', 'Tigrinya (ትግርኛ)'), ('somali', 'Somali (Soomaali)')], default='english', help_text='The language the user is learning', max_length=20),
        ),
    ]
